### ISSUE TITLE
[BUG] bool is not highlighted when used in dict literal

### ISSUE THREAD

**Issue by Jackenmen** [Sublime-Instincts/BetterJinja#12]
### Summary

`false` and `true` are not highlighted when used in dict literal.

### Expected Behaviour

I expected `false` and `true` to be highlighted as they do when used in other places in the template.

### Actual Behaviour

`false` and `true` are not highlighted:
![image](https://user-images.githubusercontent.com/6032823/150353170-a17eaf76-0f88-4349-8507-94f535351792.png)

### How to Reproduce

1. Copy paste the Jinja2 template from below.
2. Set syntax to Jinja.

### Problematic Jinja2 template.

```jinja2
{{
    lookup('file', item, errors='ignore') or {}
    | from_json
    | combine({'openAtLogin': false})
    | to_json(sort_keys=true)
}}
```

### Environment

- Sublime Text build: 4126
- BetterJinja version: v1.0.0
- Operating System: Linux

### Additional context
[The old Jinja2 package](https://github.com/kudago/jinja2-tmbundle) highlighted this properly.

**Comment by UltraInstinct05** [comment]
Thanks for the report. I plan to eventually make a bunch of improvements done to `BetterJinja` to align with the improvements made in `BetterTwig` but I don't have a specific timeline for it

**Comment by UltraInstinct05** [comment]
Can you check to see how it looks with the latest update `v1.1.0` ? It doesn't seem to happen.

![image](https://user-images.githubusercontent.com/34304644/160275339-3319fd05-be47-4466-a475-f62affd15b15.png)

**Comment by Jackenmen** [comment]
Seems like it's fixed, yeah. I'm not entirely sure why `sort_keys` keyword argument is no longer highlighted though. `errors` keyword argument in the call above still gets properly highlighted.

For comparison, Python syntax highlighting (which Jinja's mini-language is based on) highlights it like this:
![image](https://user-images.githubusercontent.com/6032823/160286135-c2fdd461-3702-4969-bc57-77a4f6d579ba.png)

**Comment by UltraInstinct05** [comment]
Thanks. I believe I understand what the issue is. I'll have this fixed (along with a number of syntax inconsistencies) in `v1.2.0`
