### ISSUE TITLE
Package Control instructions out of date?

### ISSUE THREAD

**Issue by nk9** [Sublime-Instincts/BetterJinja#15]
### Description of the bug

I go to install BJ via Package Control with the steps given in the README, and it's not listed.

I'm seeing this with ST 4126.

### Steps to reproduce

1. Cmd-Shift-P
2. Package Control: Install Package
3. Type "BetterJinja"
4. Nothing listed

I've also checked that it's not installed already, and it's not. It doesn't seem to be listed on [the PC website](https://packagecontrol.io/search/betterjinja) either.

### Expected behavior

Based on the README, I'd expect to be able to install it this way.

### Actual behavior

No installation happening. But in reality, it seems the name of the package has changed to "Jinja2". When I install that, the message says that I've installed BetterJinja v1.1.0.

### BetterJinja version

N/A

**Comment by UltraInstinct05** [comment]
Apologies for the late reply. Indeed, the repository name is `BetterJinja` but it's available as `Jinja2` on PC. The README needs to be updated with this regards.
