### ISSUE TITLE
Distributed Jinja2 package causes "Syntax Tests - All Syntaxes" to fail

### ISSUE THREAD

**Issue by nk9** [Sublime-Instincts/BetterJinja#18]
### Description of the bug

When I run `Build With: Syntax Tests - All Syntaxes` with Jinja2 installed, I get these errors:

```
Packages/Jinja2/.github/workflows/syntax_test.yml:1: unable to find SYNTAX TEST marker
Packages/Jinja2/resources/syntax/tests/syntax_test_comments.jinja:1 Error loading syntax file "Packages/BetterJinja/resources/syntax/Jinja.sublime-syntax"
Packages/Jinja2/resources/syntax/tests/syntax_test_expression_block.jinja:1 Error loading syntax file "Packages/BetterJinja/resources/syntax/Jinja.sublime-syntax"
Packages/Jinja2/resources/syntax/tests/syntax_test_filters.jinja:1 Error loading syntax file "Packages/BetterJinja/resources/syntax/Jinja.sublime-syntax"
Packages/Jinja2/resources/syntax/tests/syntax_test_regressions.jinja:1 Error loading syntax file "Packages/BetterJinja/resources/syntax/Jinja.sublime-syntax"
Packages/Jinja2/resources/syntax/tests/syntax_test_statement_blocks.jinja:1 Error loading syntax file "Packages/BetterJinja/resources/syntax/Jinja.sublime-syntax"
```

There are two problems:

- The tests are assuming that the package directory will be called BetterJinja, the name of the repo. But the package is actually installed as Jinja2. So it can't find the syntax file to run the tests on.
- Also, there's a file called `syntax_test.yml` which is actually a GitHub Action definition.

### Steps to reproduce

1. Cmd-Shift-P
2. `Build With: Syntax Tests - All Syntaxes`
3. See errors

### Expected behavior

No errors

### Actual behavior

Errors.

### BetterJinja version

1.1.0

**Comment by nk9** [comment]
There are a few solutions. The easiest would be to just exclude the files in question from the package. Indeed, when you add a package to `package_control_channel`, one of the boxes you're asked to tick says:

> I use [.gitattributes](https://www.git-scm.com/docs/gitattributes#_export_ignore) to exclude files from the package: images, test files, sublime-project/workspace.

This could go equally for the `/.git*` files, `README`, `CHANGELOG`, and `.python-version`, which serve no purpose in the distributed package.

Another option would be to change the way devs download this repo. If it were cloned locally as "Jinja2," and the tests had their `SYNTAX TEST` lines changed to use that, then it would be possible to ship the tests and have them succeed. This is the approach that seems most common in this [ST Forum thread](https://forum.sublimetext.com/t/workflow-for-plugin-development-package-control-and-github/30156/2) on package development. This would allow you to still ship the tests, which would be included when testing all syntaxes. (It's not clear to me why shipping the tests is discouraged by PackageControl when `Syntax Tests - All Syntaxes` exists.)

**Comment by keith-hall-vmp** [comment]
> * The tests are assuming that the package directory will be called BetterJinja, the name of the repo. But the package is actually installed as Jinja2.

Indeed, this is actually a little jarring - I install a package called Jinja2 from PackageControl and the Readme which appears calls the package BetterJinja. Probably the package name should be updated in PackageControlChannel and "Jinja2" be put in the "previous names".
