### ISSUE TITLE
Suggestion: CI for syntax.

### ISSUE THREAD

**Issue by ROpdebee** [Sublime-Instincts/BetterJinja#8]
Might be useful to add a CI pipeline to check the syntax definitions.

Inspiration from PackageDev:
- [Travis](https://github.com/SublimeText/PackageDev/blob/b95b906aec5d1be410d5c8161dc00a678f63ad5a/.travis.yml)
- [GH Actions](https://github.com/SublimeText/PackageDev/blob/master/.github/workflows/syntax.yml) (supports ST4)

**Comment by UltraInstinct05** [comment]
Yup. This is also on the todo list. The project was initially committed to gain some feedback from the users (and to see if any critical issues crop up, likely syntax highlighting breaking) so as to fix them.

Probably we can use https://github.com/SublimeText/syntax-test-action as well which seems like a nice boilerplate.

**Comment by UltraInstinct05** [comment]
Addressed in `v1.1.0`
